[marketplace]
enabled = false
psk = "CHANGEME"

[server.server]
port = 8080
wisp = true
logging = false

[seo]
enabled = false
domain = "https://example.com"

[db]
name = "database"
username = "username"
password = "password"
postgres = false

[postgres]
domain = ""
port = 5432

[masqr]
enabled = false
failed = "failed.html"
whitelisted = ["https://example.com"]
url = ""
